In [2]:
import numpy as np

In [3]:
a1 = np.array([1,3,4])
a1


array([1, 3, 4])

In [4]:
a2 = np.array([[1,2,4],[3.5,3,6]])
a2

array([[1. , 2. , 4. ],
       [3.5, 3. , 6. ]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a1.ndim , a2.ndim

(1, 2)

In [8]:
a1.size , a2.size

(3, 6)

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(a2)

In [ ]:
df

In [13]:
ones = np.ones((4,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
range_array = np.arange(0,12,3)

In [15]:
range_array

array([0, 3, 6, 9])

In [16]:
rand_array = np.random.randint(0,10, size=(3,5))
rand_array

array([[4, 9, 7, 8, 2],
       [3, 6, 5, 3, 8],
       [4, 2, 9, 2, 2]])

In [17]:
np.random.seed(seed = 2)
rand_array = np.random.randint(0,10, size=(3,5))
rand_array


array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6]])

In [18]:
a2

array([[1. , 2. , 4. ],
       [3.5, 3. , 6. ]])

In [19]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[4, 3, 7, 6, 1],
         [3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8]],

        [[2, 9, 8, 7, 1],
         [6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6]],

        [[5, 6, 6, 6, 3],
         [8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4]]],


       [[[5, 8, 3, 0, 0],
         [5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0]],

        [[8, 5, 4, 2, 9],
         [7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2]],

        [[5, 1, 3, 3, 1],
         [8, 6, 8, 1, 5],
         [7, 0, 9, 1, 5],
         [9, 2, 0, 0, 4]]]])

In [20]:
a4[1]

array([[[5, 8, 3, 0, 0],
        [5, 7, 5, 0, 8],
        [6, 5, 1, 7, 4],
        [3, 6, 1, 4, 0]],

       [[8, 5, 4, 2, 9],
        [7, 1, 9, 2, 1],
        [0, 7, 1, 8, 9],
        [0, 7, 0, 5, 2]],

       [[5, 1, 3, 3, 1],
        [8, 6, 8, 1, 5],
        [7, 0, 9, 1, 5],
        [9, 2, 0, 0, 4]]])

In [21]:
a4[:2,:2,:2,:2]

array([[[[4, 3],
         [3, 5]],

        [[2, 9],
         [6, 8]]],


       [[[5, 8],
         [5, 7]],

        [[8, 5],
         [7, 1]]]])

In [22]:
a4.ndim

4

In [23]:
a4

array([[[[4, 3, 7, 6, 1],
         [3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8]],

        [[2, 9, 8, 7, 1],
         [6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6]],

        [[5, 6, 6, 6, 3],
         [8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4]]],


       [[[5, 8, 3, 0, 0],
         [5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0]],

        [[8, 5, 4, 2, 9],
         [7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2]],

        [[5, 1, 3, 3, 1],
         [8, 6, 8, 1, 5],
         [7, 0, 9, 1, 5],
         [9, 2, 0, 0, 4]]]])

In [24]:
a4[1][0][0]

array([5, 8, 3, 0, 0])

In [27]:
##Manipulation

In [28]:
a1 * a2

array([[ 1. ,  6. , 16. ],
       [ 3.5,  9. , 24. ]])

In [29]:
a2 // a1

array([[1., 0., 1.],
       [3., 1., 1.]])

In [30]:
a2 / a1

array([[1.        , 0.66666667, 1.        ],
       [3.5       , 1.        , 1.5       ]])

In [31]:
np.square(a2)

array([[ 1.  ,  4.  , 16.  ],
       [12.25,  9.  , 36.  ]])

In [32]:
a2
a2.sum()

19.5

In [35]:
massive_array = np.random.random(100000)


In [36]:
massive_array[:10]

array([8.37830548e-01, 5.36453698e-01, 3.21318586e-01, 3.97253995e-01,
       2.77439216e-01, 9.36248043e-01, 4.63742607e-01, 8.52288956e-01,
       2.12767370e-01, 1.23587469e-04])

In [40]:
%timeit sum(massive_array)
print("ss")
%timeit np.sum(massive_array)

17.3 ms ± 2.56 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
ss
73.6 µs ± 4.27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
a2

array([[1. , 2. , 4. ],
       [3.5, 3. , 6. ]])

In [42]:
a3

NameError: name 'a3' is not defined

In [43]:
a2.reshape(1,6)

array([[1. , 2. , 4. , 3.5, 3. , 6. ]])

In [44]:
a2

array([[1. , 2. , 4. ],
       [3.5, 3. , 6. ]])

In [46]:
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [47]:
mat1, mat2

(array([[8, 8, 0],
        [0, 1, 5],
        [4, 1, 4],
        [0, 4, 7],
        [2, 5, 1]]),
 array([[6, 0, 8],
        [5, 2, 2],
        [0, 7, 8],
        [7, 2, 7],
        [8, 3, 6]]))

In [48]:
mat1 * mat2

array([[48,  0,  0],
       [ 0,  2, 10],
       [ 0,  7, 32],
       [ 0,  8, 49],
       [16, 15,  6]])

In [49]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [51]:
mat2 = mat2.reshape(3,5)

In [52]:
mat1, mat2

(array([[8, 8, 0],
        [0, 1, 5],
        [4, 1, 4],
        [0, 4, 7],
        [2, 5, 1]]),
 array([[6, 0, 8, 5, 2],
        [2, 0, 7, 8, 7],
        [2, 7, 8, 3, 6]]))

In [53]:
np.dot(mat1,mat2)

array([[ 64,   0, 120, 104,  72],
       [ 12,  35,  47,  23,  37],
       [ 34,  28,  71,  40,  39],
       [ 22,  49,  84,  53,  70],
       [ 24,   7,  59,  53,  45]])

In [54]:
a1 < 2

array([ True, False, False])

In [55]:
rand_array

array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6]])

In [57]:
np.sort(rand_array)

array([[2, 6, 8, 8, 8],
       [1, 2, 4, 5, 7],
       [3, 4, 5, 6, 7]])

In [59]:
<img src = "panda.png">

SyntaxError: invalid syntax (<ipython-input-59-7eadef16dbbd>, line 1)

In [60]:
from matplotlib.image import imread

panda = imread("panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [61]:
panda.shape

(2330, 3500, 3)

In [63]:
panda.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [66]:
car = imread("car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [67]:
dog = imread("dog-photo.png")

In [68]:
dog


array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274